### PR TITLE
Set up frontend routing and homepage

### LINKED ISSUE #8: create index.html/ home page using wireframe.
how do y'all feel about the homepage having the following:

image
^^ for the portion that says 'you must be logged in..." that part could be overlayed onto the background, and then the background can be blurred. this way it's simulating how some sites need you to pay before using a product. except, in this case, we need them to log-in to start using it.

- other things to note:
   -  the home page can be one continuous scroll, so that when the user clicks on add, or view at the top right, it will JUMP to that section
  - how do you all feel about making the add template be at the top of the homepage, like the image below:

image

^^ instead, we would replace title with name, and modify it to have the items we talked about:
- name,
- email/contact, etc.

and then when the user clicks on contact book, it would jump to this:
image
and on the side we can ask if the user wants to see it in a different view.  this would mean that global view will be the default. 
finally, at the bottom, it can be a little copyright/license section where our names are at the bottom, to ackowledge that we made it.

### PR DESCRIPTION
**Pull request by amy-lei**
Small changes but will be helpful for future pages
- Added material-ui and react-simple-maps to package.json
- Set up react routing for non API endpoints
- Create and style homepage (no functionality for now but designed a nice background :smile:)
image

### CODE REVIEW

**Review by FawziyahAlebiosu — CHANGES_REQUESTED** [review]
amy!!! this looks beautiful and simple and minimalist!! i want your eye for design :/ one very tiny quick change though, can we add a sign up button right next to the log-in button?

**Comment by amy-lei** [comment]
> amy!!! this looks beautiful and simple and minimalist!! i want your eye for design :/ one very tiny quick change though, can we add a sign up button right next to the log-in button?

Yep, we can do that. I just wasn't sure if we're sticking with our own auth or using something like google auth/github auth. I wouldn't know how to handle "sign up"s in that case, but for now we can stick with the auth Ebonne had set up.

**Comment by amy-lei** [comment]
@FawziyahAlebiosu  made the changes!

**Comment by FawziyahAlebiosu** [comment]
Looks good to me!

**Review by FawziyahAlebiosu — APPROVED** [review]

**Comment by ebonnecab** [comment]
The register function in the auth file stores them as users in the DB and just redirects them back to the homepage. It should be pretty simple to get them connected, I'll work on it on my branch

**Pull request merged**
