### PR TITLE
New db

### PR DESCRIPTION
**Pull request by ebonnecab**
Okay, i added the code for authorization and it seems to be fully functional on my end. Checkout my changes and see if everything works on your end

### CODE REVIEW

**Review by amy-lei — APPROVED** [review]
:)) Wooo good job!! A few notes (nothing major so I'll still approve, plus we're in a time crunch. I'll include this in an issue):
- For users, are we switching over to email instead of username? Regardless, we should check if the email/username is already registered so no users can have two+ accounts
- If you have time, can you add docstrings as to what should be in the body/params of the request, and the format of what is returned? 
- How does the token work? (in the case where the user was already logged in. Is it possible to make an endpoint separate from /login? Then, on the frontend, the first thing i do is send a request to check before directing to the login/register page vs all contacts page.

**Review by FawziyahAlebiosu — APPROVED** [review]
Ebonne!! Your mind!! It works on my computer as well, and I can see the homepage. You really,really pulled through with the backend.

**Comment by ebonnecab** [comment]
- I changed it to ask for username and full name instead. I don't think we need the email now that I think about it. the unique=True parameter should prevent them from being able to make two accounts with the same username.
- I'm working on the doc strings now, I'll send it over when I'm finished before I push
- The token stays activated for 7 days once they login. when the token expires, they have to login again. As far as a separate endpoint, do you mean like straight to the contacts? I feel like you can check for a token and decide which page to send them to?

**Comment by ebonnecab** [comment]
> Ebonne!! Your mind!! It works on my computer as well, and I can see the homepage. You really,really pulled through with the backend.

Thank you! :)) I found some really good documentation

**Comment by ebonnecab** [comment]
you should see the changes that I just implemented minus the docstrings

**Pull request merged**
